###
GET http://localhost:9000/api HTTP/1.1

###
POST http://localhost:3000/api HTTP/1.1
Content-Type: application/json

{
  "NAME": "A",
  "LAST_NAME": "E",
  "TYPE_DOCUMENT": "ti",
  "DOCUMENT": "1010152996",
  "STATE": "a",
  "CREATION_DATE": "2021/12/31 23:59:59"
}

###
PATCH  http://localhost:9000/api/2 HTTP/1.1

###
PUT http://localhost:000/api/1 HTTP/1.1
Content-Type: application/json

{
  "nombre": "Farid",
  "apellido": "Valbuena",
  "tipo de documento": "ti",
  "numero de documento": "1010152996",
  "estado": "a",
  "fecha creacion":"2021-12-31 23:59:59"
}