###
GET http://localhost:3000/api/ HTTP/1.1
Content-Type: application/json

{
  "id": 2
}

###
GET http://localhost:3000/api/name HTTP/1.1
Content-Type: application/json

{
  "name": "Farid"
}

###
GET http://localhost:3000/api/name HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/login HTTP/1.1



###
POST http://localhost:3000/api HTTP/1.1
Content-Type: application/json

{
  "NAME": "prueba",
  "LAST_NAME": "pass",
  "TYPE_DOCUMENT": "cc",
  "DOCUMENT": "12",
  "STATE": "a",
  "PASSWORD":"12345"
}

###
PATCH  http://localhost:9000/api/2 HTTP/1.1

###
PUT http://localhost:000/api/1 HTTP/1.1
Content-Type: application/json

{
  "nombre": "Farid",
  "apellido": "Valbuena",
  "tipo de documento": "ti",
  "numero de documento": "1010152996",
  "estado": "a",
  "fecha creacion":"2021-12-31 23:59:59"
}