-- CreateTable
CREATE TABLE `log_connection` (
    `ID_USSERS_ROL` INTEGER NOT NULL AUTO_INCREMENT,
    `INITIAL_DATE` DATETIME(0) NOT NULL,
    `FINAL_DATE` DATETIME(0) NOT NULL,
    `STATE` CHAR(2) NOT NULL,
    `ID_USUARIOS` INTEGER NOT NULL,

    INDEX `ID_USSUARIOS_idx`(`ID_USUARIOS`),
    PRIMARY KEY (`ID_USSERS_ROL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `log_connection` ADD CONSTRAINT `ID_USSUARIOS` FOREIGN KEY (`ID_USUARIOS`) REFERENCES `usuarios`(`ID_USUARIOS`) ON DELETE NO ACTION ON UPDATE NO ACTION;
